// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Processos_Juridicos.Entities2;

public partial class Processos_DJContext : DbContext
{
    public Processos_DJContext(DbContextOptions<Processos_DJContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Accident_types> Accident_types { get; set; }

    public virtual DbSet<Files> Files { get; set; }

    public virtual DbSet<Harmed_or_casualties> Harmed_or_casualties { get; set; }

    public virtual DbSet<Infringements> Infringements { get; set; }

    public virtual DbSet<Process_types> Process_types { get; set; }

    public virtual DbSet<Processes> Processes { get; set; }

    public virtual DbSet<Sentences> Sentences { get; set; }

    public virtual DbSet<States> States { get; set; }

    public virtual DbSet<Units> Units { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Process_types>(entity =>
        {
            entity.HasKey(e => e.process_type_id).HasName("PK_Process_type");
        });

        modelBuilder.Entity<Processes>(entity =>
        {
            entity.HasOne(d => d.harmed_or_casualties).WithMany(p => p.Processes).HasConstraintName("FK_Processes_Harmed_or_casualties");

            entity.HasOne(d => d.infringement).WithMany(p => p.Processes).HasConstraintName("FK_Processes_Infringements");

            entity.HasOne(d => d.process_type).WithMany(p => p.Processes).HasConstraintName("FK_Processes_Process_types");

            entity.HasOne(d => d.sentence).WithMany(p => p.Processes).HasConstraintName("FK_Processes_Sentences");

            entity.HasOne(d => d.service_accident).WithMany(p => p.Processes).HasConstraintName("FK_Processes_Accident_types");

            entity.HasOne(d => d.state).WithMany(p => p.Processes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Processes_States");

            entity.HasOne(d => d.unit).WithMany(p => p.Processes).HasConstraintName("FK_Processes_Units");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}