// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Processos_Juridicos.Entities2;

public partial class Units
{
    [Key]
    public int unit_id { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string unit_name { get; set; }

    [InverseProperty("unit")]
    public virtual ICollection<Processes> Processes { get; set; } = new List<Processes>();
}