// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Processos_Juridicos.Data;

#nullable disable

namespace Processos_Juridicos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260417103303_MandatoryDeclaration")]
    partial class MandatoryDeclaration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InfringementProcess", b =>
                {
                    b.Property<int>("InfringementsInfringementId")
                        .HasColumnType("int");

                    b.Property<int>("ProcessesProcessId")
                        .HasColumnType("int");

                    b.HasKey("InfringementsInfringementId", "ProcessesProcessId");

                    b.HasIndex("ProcessesProcessId");

                    b.ToTable("InfringementProcess");
                });

            modelBuilder.Entity("Processos_Juridicos.Entities.AccidentType", b =>
                {
                    b.Property<int>("AccidentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("accident_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccidentTypeId"));

                    b.Property<string>("AccidentTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("accident_type");

                    b.HasKey("AccidentTypeId");

                    b.ToTable("Accident_types");
                });

            modelBuilder.Entity("Processos_Juridicos.Entities.CrimeType", b =>
                {
                    b.Property<int>("CrimeTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("crime_type_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CrimeTypeId"));

                    b.Property<string>("CrimeTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("crime_type_name");

                    b.HasKey("CrimeTypeId");

                    b.ToTable("Crime_types");
                });

            modelBuilder.Entity("Processos_Juridicos.Entities.HarmedOrCasualty", b =>
                {
                    b.Property<int>("CasualtyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("casualties_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CasualtyId"));

                    b.Property<string>("CasualtyName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("casualties_name");

                    b.HasKey("CasualtyId");

                    b.ToTable("Harmed_or_casualties");
                });

            modelBuilder.Entity("Processos_Juridicos.Entities.Infringement", b =>
                {
                    b.Property<int>("InfringementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("infringement_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InfringementId"));

                    b.Property<string>("InfringementName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("infringement_name");

                    b.HasKey("InfringementId");

                    b.ToTable("Infringements");
                });

            modelBuilder.Entity("Processos_Juridicos.Entities.MilitarySecurity", b =>
                {
                    b.Property<int>("MilitarySecurityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("military_security_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MilitarySecurityId"));

                    b.Property<string>("MilitarySecurityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("military_security_name");

                    b.HasKey("MilitarySecurityId");

                    b.ToTable("Military_securities");
                });

            modelBuilder.Entity("Processos_Juridicos.Entities.Process", b =>
                {
                    b.Property<int>("ProcessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("process_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProcessId"));

                    b.Property<int?>("CompensatingUnitId")
                        .HasColumnType("int")
                        .HasColumnName("compensating_unit_id");

                    b.Property<bool>("CompensationPaid")
                        .HasColumnType("bit")
                        .HasColumnName("compensation_paid_by_unit");

                    b.Property<bool>("ComunicatedToPjm")
                        .HasColumnType("bit")
                        .HasColumnName("comunicated_pjm");

                    b.Property<DateOnly?>("ComunicationDate")
                        .HasColumnType("date")
                        .HasColumnName("pjm_comunication_date");

                    b.Property<DateOnly?>("CreatedAt")
                        .HasColumnType("date")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by_name");

                    b.Property<string>("CreatedByNii")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("created_by_nii");

                    b.Property<int?>("CrimeTypeId")
                        .HasColumnType("int")
                        .HasColumnName("crime_type_id");

                    b.Property<DateOnly?>("DeadlineDate")
                        .HasColumnType("date")
                        .HasColumnName("deadline_date");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("DispatchDate")
                        .HasColumnType("date")
                        .HasColumnName("dispatch_date");

                    b.Property<DateOnly?>("FinalDispatchDate")
                        .HasColumnType("date")
                        .HasColumnName("final_dispatch_date");

                    b.Property<int?>("HarmedOrCasualtiesId")
                        .HasColumnType("int")
                        .HasColumnName("harmed_or_casualties_id");

                    b.Property<int?>("InterestConflictDeclarationId")
                        .HasColumnType("int")
                        .HasColumnName("interest_conflict_declaration_id");

                    b.Property<string>("InvestigatedGender")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("investigated_gender");

                    b.Property<string>("InvestigatedName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("investigated_name");

                    b.Property<bool>("InvestigatedUncertain")
                        .HasColumnType("bit")
                        .HasColumnName("investigated_uncertain");

                    b.Property<string>("JuristName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("jurist_name");

                    b.Property<int?>("MilitarySecurityId")
                        .HasColumnType("int")
                        .HasColumnName("military_security_id");

                    b.Property<DateOnly?>("ModifiedAt")
                        .HasColumnType("date")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("modified_by_name");

                    b.Property<string>("ModifiedByNii")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("modified_by_nii");

                    b.Property<string>("Nuipm")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nuipm");

                    b.Property<DateOnly?>("OcurrenceDate")
                        .HasColumnType("date")
                        .HasColumnName("occurrence_date");

                    b.Property<string>("OficialInstName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("oficial_inst_name");

                    b.Property<string>("OficialInstNii")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("oficial_inst_nii");

                    b.Property<string>("OficialInstTelephone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("oficial_inst_telephone");

                    b.Property<int>("ProcessStateId")
                        .HasColumnType("int")
                        .HasColumnName("state_id");

                    b.Property<int?>("ProcessTypeId")
                        .HasColumnType("int")
                        .HasColumnName("process_type_id");

                    b.Property<double?>("Reimbursement")
                        .HasColumnType("float")
                        .HasColumnName("reimbursement");

                    b.Property<int?>("SentenceId")
                        .HasColumnType("int")
                        .HasColumnName("sentence_id");

                    b.Property<int?>("ServiceAccidentId")
                        .HasColumnType("int")
                        .HasColumnName("service_accident_id");

                    b.Property<double?>("ThirdPartyCompensation")
                        .HasColumnType("float")
                        .HasColumnName("third_party_compensation");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int")
                        .HasColumnName("unit_id");

                    b.HasKey("ProcessId");

                    b.HasIndex("CompensatingUnitId");

                    b.HasIndex("CreatedByNii");

                    b.HasIndex("CrimeTypeId");

                    b.HasIndex("HarmedOrCasualtiesId");

                    b.HasIndex("InterestConflictDeclarationId");

                    b.HasIndex("MilitarySecurityId");

                    b.HasIndex("ModifiedByNii");

                    b.HasIndex("OficialInstNii");

                    b.HasIndex("ProcessStateId");

                    b.HasIndex("ProcessTypeId");

                    b.HasIndex("SentenceId");

                    b.HasIndex("ServiceAccidentId");

                    b.HasIndex("UnitId");

                    b.ToTable("Processes");
                });

            modelBuilder.Entity("Processos_Juridicos.Entities.ProcessFile", b =>
                {
                    b.Property<int>("ProcessFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("process_file_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProcessFileId"));

                    b.Property<byte[]>("ProcessFileContent")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("process_file_content");

                    b.Property<string>("ProcessFileName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("process_file_name");

                    b.Property<string>("ProcessFileTrustedName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("process_file_trusted_name");

                    b.Property<string>("ProcessFileType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("process_file_type");

                    b.Property<int>("ProcessId")
                        .HasColumnType("int")
                        .HasColumnName("process_id");

                    b.HasKey("ProcessFileId");

                    b.HasIndex("ProcessId");

                    b.ToTable("Process_files");
                });

            modelBuilder.Entity("Processos_Juridicos.Entities.ProcessState", b =>
                {
                    b.Property<int>("ProcessStateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("state_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProcessStateId"));

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("state_name");

                    b.HasKey("ProcessStateId");

                    b.ToTable("Process_states");
                });

            modelBuilder.Entity("Processos_Juridicos.Entities.ProcessType", b =>
                {
                    b.Property<int>("ProcessTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("process_type_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProcessTypeId"));

                    b.Property<int>("Deadline")
                        .HasColumnType("int")
                        .HasColumnName("deadline");

                    b.Property<string>("ProcessTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("process_name");

                    b.HasKey("ProcessTypeId");

                    b.ToTable("Process_types");
                });

            modelBuilder.Entity("Processos_Juridicos.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Processos_Juridicos.Entities.Sentence", b =>
                {
                    b.Property<int>("SentenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("sentence_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SentenceId"));

                    b.Property<string>("SentenceName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sentence_name");

                    b.HasKey("SentenceId");

                    b.ToTable("Sentences");
                });

            modelBuilder.Entity("Processos_Juridicos.Entities.StateTransition", b =>
                {
                    b.Property<int>("StateTransitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("state_transition_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StateTransitionId"));

                    b.Property<int>("FromStateId")
                        .HasColumnType("int")
                        .HasColumnName("from_state_id");

                    b.Property<int>("ToStateId")
                        .HasColumnType("int")
                        .HasColumnName("to_state_id");

                    b.HasKey("StateTransitionId");

                    b.HasIndex("ToStateId");

                    b.HasIndex("FromStateId", "ToStateId")
                        .IsUnique();

                    b.ToTable("State_transitions");
                });

            modelBuilder.Entity("Processos_Juridicos.Entities.StateTransitionRole", b =>
                {
                    b.Property<int>("StateTransitionId")
                        .HasColumnType("int")
                        .HasColumnName("state_transition_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.HasKey("StateTransitionId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("State_transition_roles");
                });

            modelBuilder.Entity("Processos_Juridicos.Entities.Unit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("unit_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnitId"));

                    b.Property<bool>("CanCompensate")
                        .HasColumnType("bit")
                        .HasColumnName("can_compensate");

                    b.Property<bool>("Enable")
                        .HasColumnType("bit")
                        .HasColumnName("enable");

                    b.Property<string>("UnitAcronym")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("unit_acronym");

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("unit_code");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("unit_name");

                    b.HasKey("UnitId");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("Processos_Juridicos.Entities.UnitCommander", b =>
                {
                    b.Property<int>("UnitId")
                        .HasColumnType("int")
                        .HasColumnName("unit_id");

                    b.Property<string>("UserNii")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("user_nii");

                    b.HasKey("UnitId", "UserNii");

                    b.HasIndex("UserNii");

                    b.ToTable("Unit_commanders", (string)null);
                });

            modelBuilder.Entity("Processos_Juridicos.Entities.User", b =>
                {
                    b.Property<string>("UserNii")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("user_nii");

                    b.Property<bool>("IsUserManuallySet")
                        .HasColumnType("bit")
                        .HasColumnName("is_manually_set");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("user_role");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_name");

                    b.HasKey("UserNii");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("InfringementProcess", b =>
                {
                    b.HasOne("Processos_Juridicos.Entities.Infringement", null)
                        .WithMany()
                        .HasForeignKey("InfringementsInfringementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Processos_Juridicos.Entities.Process", null)
                        .WithMany()
                        .HasForeignKey("ProcessesProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Processos_Juridicos.Entities.Process", b =>
                {
                    b.HasOne("Processos_Juridicos.Entities.Unit", "CompensatingUnit")
                        .WithMany()
                        .HasForeignKey("CompensatingUnitId");

                    b.HasOne("Processos_Juridicos.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByNii");

                    b.HasOne("Processos_Juridicos.Entities.CrimeType", "CrimeType")
                        .WithMany()
                        .HasForeignKey("CrimeTypeId");

                    b.HasOne("Processos_Juridicos.Entities.HarmedOrCasualty", "HarmedOrCasualties")
                        .WithMany()
                        .HasForeignKey("HarmedOrCasualtiesId");

                    b.HasOne("Processos_Juridicos.Entities.ProcessFile", "InterestConflictDeclaration")
                        .WithMany()
                        .HasForeignKey("InterestConflictDeclarationId");

                    b.HasOne("Processos_Juridicos.Entities.MilitarySecurity", "MilitarySecurity")
                        .WithMany()
                        .HasForeignKey("MilitarySecurityId");

                    b.HasOne("Processos_Juridicos.Entities.User", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedByNii");

                    b.HasOne("Processos_Juridicos.Entities.User", "OficialInstrutor")
                        .WithMany()
                        .HasForeignKey("OficialInstNii");

                    b.HasOne("Processos_Juridicos.Entities.ProcessState", "ProcessState")
                        .WithMany()
                        .HasForeignKey("ProcessStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Processos_Juridicos.Entities.ProcessType", "ProcessType")
                        .WithMany()
                        .HasForeignKey("ProcessTypeId");

                    b.HasOne("Processos_Juridicos.Entities.Sentence", "Sentence")
                        .WithMany()
                        .HasForeignKey("SentenceId");

                    b.HasOne("Processos_Juridicos.Entities.AccidentType", "AccidentType")
                        .WithMany()
                        .HasForeignKey("ServiceAccidentId");

                    b.HasOne("Processos_Juridicos.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId");

                    b.Navigation("AccidentType");

                    b.Navigation("CompensatingUnit");

                    b.Navigation("CreatedBy");

                    b.Navigation("CrimeType");

                    b.Navigation("HarmedOrCasualties");

                    b.Navigation("InterestConflictDeclaration");

                    b.Navigation("MilitarySecurity");

                    b.Navigation("ModifiedBy");

                    b.Navigation("OficialInstrutor");

                    b.Navigation("ProcessState");

                    b.Navigation("ProcessType");

                    b.Navigation("Sentence");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Processos_Juridicos.Entities.ProcessFile", b =>
                {
                    b.HasOne("Processos_Juridicos.Entities.Process", "Process")
                        .WithMany()
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Process");
                });

            modelBuilder.Entity("Processos_Juridicos.Entities.StateTransition", b =>
                {
                    b.HasOne("Processos_Juridicos.Entities.ProcessState", "FromState")
                        .WithMany()
                        .HasForeignKey("FromStateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Processos_Juridicos.Entities.ProcessState", "ToState")
                        .WithMany()
                        .HasForeignKey("ToStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromState");

                    b.Navigation("ToState");
                });

            modelBuilder.Entity("Processos_Juridicos.Entities.StateTransitionRole", b =>
                {
                    b.HasOne("Processos_Juridicos.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Processos_Juridicos.Entities.StateTransition", "StateTransition")
                        .WithMany("Roles")
                        .HasForeignKey("StateTransitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("StateTransition");
                });

            modelBuilder.Entity("Processos_Juridicos.Entities.UnitCommander", b =>
                {
                    b.HasOne("Processos_Juridicos.Entities.Unit", "Unit")
                        .WithMany("UnitCommanders")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Processos_Juridicos.Entities.User", "User")
                        .WithMany("UnitCommanders")
                        .HasForeignKey("UserNii")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Processos_Juridicos.Entities.User", b =>
                {
                    b.HasOne("Processos_Juridicos.Entities.Role", "UserRole")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("Processos_Juridicos.Entities.StateTransition", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Processos_Juridicos.Entities.Unit", b =>
                {
                    b.Navigation("UnitCommanders");
                });

            modelBuilder.Entity("Processos_Juridicos.Entities.User", b =>
                {
                    b.Navigation("UnitCommanders");
                });
#pragma warning restore 612, 618
        }
    }
}
