name: PR SonarQube Analysis

on:
  pull_request:
    types: [opened, reopened, synchronize]

env:
  RUNNER_TOOL_CACHE: /toolcache

jobs:
  pr-sonarscan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.SSH_KEY }}
          ssh-known-hosts: ${{ vars.SSH_KNOWN_HOSTS }}

      - name: Setup .NET 8.0.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install SonarQube scanner + coverlet
        run: |
          mkdir -p .sonar/scanner
          dotnet tool update dotnet-sonarscanner --tool-path ./.sonar/scanner
          dotnet tool update coverlet.console --tool-path ./.sonar/coverage

      - name: Begin SonarQube Analysis
        run: |
          ./.sonar/scanner/dotnet-sonarscanner begin \
            /k:processos-juridicos \
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.host.url="${{ vars.SONAR_HOST_URL }}" \
            /d:sonar.cs.opencover.reportsPaths=coverage.opencover.xml \
            /d:sonar.javascript.lcov.reportPaths=$(pwd)/coverage/lcov.info \
            /d:sonar.pullrequest.key=${{ gitea.event.number }} \
            /d:sonar.pullrequest.branch=${{ gitea.head_ref }} \
            /d:sonar.pullrequest.base=${{ gitea.base_ref }} \
            /d:sonar.sources=. \
            /d:sonar.exclusions="**/.devcontainer/**,**/Migrations/**,**/bin/**,**/obj/**" \
            /d:sonar.scanner.scanAll=false

      - name: Build for SonarQube (no incremental)
        run: dotnet build --no-incremental

      - name: Run C# tests with coverage
        run: |
          mkdir -p coverage
          dotnet coverlet ./Processos_Juridicos.Tests/bin/Debug/net8.0/Processos_Juridicos.Tests.dll \
            --target dotnet \
            --targetargs "test --no-build" \
            -f=opencover \
            -o="coverage.opencover.xml"

      - name: Run JS tests with coverage
        run: |
          npm ci
          # force vitest to write its lcov into the same coverage folder
          npx vitest run --coverage --coverage.reportsDirectory=coverage

      - name: Normalize LCOV paths
        run: |
           sed -i 's#^SF:Processos-Juridicos/wwwroot/#SF:wwwroot/#' coverage/lcov.info


      - name: End SonarQube Analysis
        run: ./.sonar/scanner/dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
          scanMetadataReportFile: .sonarqube/out/.sonar/report-task.txt
          pollingTimeoutSec: 600
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
