name: Release
on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      http_proxy: ${{ vars.PROXY }}
      https_proxy: ${{ vars.PROXY }}
      no_proxy: ${{ vars.NO_PROXY }}
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.SSH_KEY }}
          ssh-known-hosts: ${{ vars.SSH_KNOWN_HOSTS }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm clean-install

      - name: Setup .NET 10.0.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Publish
        run: dotnet publish Processos-Juridicos/Processos-Juridicos.csproj

      - name: Package published files
        run: |
          cd Processos-Juridicos/bin
          tar -czf processos-juridicos.tar.gz -C ./Release .
        shell: bash

      - name: Prepare ROOT-CA-CA certificate
        run: |
          mkdir -p certs
          echo "${{ vars.ROOT_CA_CA_ENCODED }}" | openssl base64 -d -out certs/root-ca-ca.crt
          echo "✅ Certificate information:"
          openssl x509 -in "certs/root-ca-ca.crt" -text -noout

      - name: Prepare MARINHA-ROOT-CA certificate
        run: |
          echo "${{ vars.MARINHA_ROOT_CA_ENCODED }}" | openssl base64 -d -out certs/marinha-root-ca.crt
          echo "✅ Certificate information:"
          openssl x509 -in "certs/marinha-root-ca.crt" -text -noout

      - name: Release
        env:
          GITEA_TOKEN: ${{ secrets.PACKAGE_UPLOAD_TOKEN }}
          GITEA_URL: https://devops-01.marinha.pt
          NODE_EXTRA_CA_CERTS: '${{ github.workspace }}/certs/marinha-root-ca.crt'
          DOCKER_REGISTRY_USER: "${{ vars.USERNAME }}"
          DOCKER_REGISTRY_PASSWORD: ${{ secrets.PACKAGE_UPLOAD_TOKEN }}
        run: |
          npx semantic-release