// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Processos_Juridicos.Entities;

public partial class AccidentType
{
    [Key]
    [Required]
    [Column("accident_id")]
    public int AccidentId { get; set; }

    [Required]
    [Column("accident_type")]
    public string AccidentName { get; set; }

    public ICollection<Process> Processes { get; set; } = new List<Process>();
}