// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Processos_Juridicos.Entities;

public partial class CrimeType
{
    [Key]
    [Required]
    [Column("crime_type_id")]
    public int CrimeTypeId { get; set; }

    [Required]
    [Column("crime_type_name")]
    public string CrimeTypeName { get; set; }

    public ICollection<Process> Processes { get; set; } = new List<Process>();
}