// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Processos_Juridicos.Entities;

public partial class Files
{
    [Key]
    public int file_id { get; set; }

    public string file_name { get; set; }

    public string file_type { get; set; }

    public byte[] file_content { get; set; }

    public int process_id { get; set; }

    public int row_guid { get; set; }
}