// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Processos_Juridicos.Entities;

public partial class Files
{
    public int FileId { get; set; }

    public string FileName { get; set; }

    public string FileType { get; set; }

    public byte[] FileContent { get; set; }

    public int ProcessId { get; set; }

    public int RowGuid { get; set; }
}