// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Processos_Juridicos.Entities;

public partial class Harmed_or_casualties
{
    [Key]
    public int casualties_id { get; set; }

    public string casualties_name { get; set; }

    public virtual ICollection<Processes> Processes { get; set; } = new List<Processes>();
}