// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Processos_Juridicos.Entities;

public partial class HarmedOrCasualty
{
    [Key]
    [Column("casualties_id")]
    public int CasualtiesId { get; set; }

    [Column("casualties_name")]
    public string CasualtiesName { get; set; }
   
    public virtual ICollection<Process> Processes { get; set; } = new List<Process>();
}