// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Processos_Juridicos.Entities;

public partial class Infringement
{
    [Key]
    [Column("infringement_id")]
    public int InfringementId { get; set; }
    [Column("infringement_name")]
    public string InfringementName { get; set; }
    public  ICollection<Process> Processes { get; set; } = new List<Process>();
}