// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Processos_Juridicos.Entities;

public partial class Processes
{
    [Key]
    public int process_id { get; set; }

    public int? nuipm { get; set; }

    public int? process_type_id { get; set; }

    public int? unit_id { get; set; }

    public int? oficial_inst_id { get; set; }

    public int? investigated_id { get; set; }

    public int? investigated_gender_id { get; set; }

    public DateOnly? occurrence_date { get; set; }

    public DateOnly? dispatch_date { get; set; }

    public string description { get; set; }

    public DateOnly? deadline_date { get; set; }

    public DateOnly? final_dispatch_date { get; set; }

    public int? sentence_id { get; set; }

    public int state_id { get; set; }

    public DateOnly? created_at { get; set; }

    public int? created_by_id { get; set; }

    public DateOnly? modified_at { get; set; }

    public int? modified_by_id { get; set; }

    public int? service_accident_id { get; set; }

    public int? harmed_or_casualties_id { get; set; }

    public double? third_party_compensation { get; set; }

    public double? reimbursement { get; set; }

    public int? infringement_id { get; set; }


    [ForeignKey("harmed_or_casualties_id")]
    [InverseProperty("Processes")]
    public  Harmed_or_casualties harmed_or_casualties { get; set; }

    [ForeignKey("infringement_id")]
    [InverseProperty("Processes")]
    public  Infringements infringement { get; set; }

    [ForeignKey("process_type_id")]
    [InverseProperty("Processes")]
    public  Process_types process_type { get; set; }

    [ForeignKey("sentence_id")]
    [InverseProperty("Processes")]
    public  Sentences sentence { get; set; }

    [ForeignKey("service_accident_id")]
    [InverseProperty("Processes")]
    public  Accident_types service_accident { get; set; }

    [ForeignKey("state_id")]
    [InverseProperty("Processes")]
    public  States state { get; set; }

    [ForeignKey("unit_id")]
    [InverseProperty("Processes")]
    public  Units unit { get; set; }
}