// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Processos_Juridicos.Entities;

public partial class Process_types
{
    [Key]
    public int process_type_id { get; set; }

    public string process_name { get; set; }

    [DisplayName("Data limite")]
    public int deadline { get; set; }

    public virtual ICollection<Processes> Processes { get; set; } = new List<Processes>();
}