// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Processos_Juridicos.Entities;

public partial class ProcessType
{
    [Key]
    [Required]
    [Column("process_type_id")]
    public int ProcessTypeId { get; set; }

    [Required]
    [Column("process_name")]
    public string ProcessTypeName { get; set; }

    [Required]
    [Column("deadline")]
    public int Deadline { get; set; }

    public virtual ICollection<Process> Processes { get; set; } = new List<Process>();
}