// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Processos_Juridicos.Entities;

public partial class ProcessTypes
{
    public int ProcessTypeId { get; set; }

    public string ProcessName { get; set; }

    public virtual ICollection<Processes> Processes { get; set; } = new List<Processes>();
}