// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Processos_Juridicos.Entities;

public partial class Processes
{
    public int ProcessId { get; set; }

    public int? Nuipm { get; set; }

    public int? ProcessTypeId { get; set; }

    public int? UnitId { get; set; }

    public int? OficialInstId { get; set; }

    public int? InvestigatedId { get; set; }

    public int? InvestigatedGenderId { get; set; }

    public DateOnly? OccurrenceDate { get; set; }

    public DateOnly? DispatchDate { get; set; }

    public string Description { get; set; }

    public DateOnly? DeadlineDate { get; set; }

    public DateOnly? FinalDispatchDate { get; set; }

    public int? SentenceId { get; set; }

    public int StateId { get; set; }

    public DateOnly? CreatedAt { get; set; }

    public int? CreatedById { get; set; }

    public DateOnly? ModifiedAt { get; set; }

    public int? ModifiedById { get; set; }

    public int? ServiceAccidentId { get; set; }

    public int? HarmedOrCasualtiesId { get; set; }

    public double? ThirdPartyCompensation { get; set; }

    public double? Reimbursement { get; set; }

    public int? InfringementId { get; set; }

    public virtual HarmedOrCasualties HarmedOrCasualties { get; set; }

    public virtual Infringements Infringement { get; set; }

    public virtual ProcessTypes ProcessType { get; set; }

    public virtual Sentences Sentence { get; set; }

    public virtual AccidentTypes ServiceAccident { get; set; }

    public virtual States State { get; set; }

    public virtual Units Unit { get; set; }
}