// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Processos_Juridicos.Entities;

public partial class ProcessFile
{
    [Key]
    [Column("process_file_id")]
    public int ProcessFileId { get; set; }

    [Column("process_file_name")]
    public string ProcessFileName { get; set; }

    [Column("process_file_type")]
    public string ProcessFileType { get; set; }

    [Column("process_file_content")]
    public byte[] ProcessFileContent { get; set; }

    [Column("process_id")]
    public int ProcessId { get; set; }

    [Column("row_guid")]
    public int RowGuid { get; set; }
}