// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Processos_Juridicos.Entities;

public partial class Sentence
{
    [Key]
    [Column("sentence_id")]
    public int SentenceId { get; set; }

    [Column("sentence_name")]
    public string SentenceName { get; set; }

    public ICollection<Process> Processes { get; set; } = new List<Process>();
}