// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Processos_Juridicos.Entities;

public partial class States
{
    [Key]
    public int state_id { get; set; }

    public string state_name { get; set; }

    public ICollection<Processes> Processes { get; set; } = new List<Processes>();
}