// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Processos_Juridicos.Entities;

public class Units
{
    [Key]
    [DisplayName("Código da unidade")]
    public string unit_code { get; set; }

    [DisplayName("Nome da unidade")]
    public string unit_name { get; set; }
    [DisplayName("Abreviatura")]
    public string unit_acronym { get; set; }
    public string sector_code { get; set; }


    [ForeignKey(" sector_code")]
    public Sectors Sectors { get; set; }
    public  ICollection<Processes> Processes { get; set; } = new List<Processes>();
}