// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Processos_Juridicos.Entities;

public partial class Units
{
    [Key]
    public string unit_code { get; set; }

    public string unit_name { get; set; }

    public string unit_acronym { get; set; }

    public string sector_code { get; set; }

    public virtual ICollection<Processes> Processes { get; set; } = new List<Processes>();
}