// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Processos_Juridicos.Entities;

public class Units
{
    [Key]
    public int unit_id { get; set; }

    [DisplayName("Código da unidade")]
    public string unit_code { get; set; }
    public string unit_name { get; set; }
    public string unit_acronym { get; set; }
    public int sector_Id { get; set; }
    public bool Enable { get; set; } = default;

    [ForeignKey("sector_Id")]
    public Sectors Sectors { get; set; }
    public  ICollection<Processes> Processes { get; set; } = new List<Processes>();
}