// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Processos_Juridicos.DTOs;

public partial class AccidentTypeDto
{
    [Key]
    [Required]
    public int AccidentId { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    [Required(ErrorMessage = "O tipo de acidente é obrigatório")]
    [DisplayName("Tipo de Acidente")]
    public string AccidentName { get; set; }

    [InverseProperty("service_accident")]
    public virtual ICollection<ProcessDto> Processes { get; set; } = new List<ProcessDto>();
}