// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Processos_Juridicos.Attributes;

namespace Processos_Juridicos.DTOs;

public partial class CrimeTypeDto
{
    [Key]
    [Required]
    public int CrimeTypeId { get; set; }

    [Unicode(false)]
    [Required(ErrorMessage = "O Tipo de Crime é obrigatório")]
    [StringLength(50, ErrorMessage = "O campo {0} deve ter no máximo {1} caracteres")]
    [DisplayName("Tipo de Crime")]
    [UniqueCrimeTypeName]
    public string CrimeTypeName { get; set; }

    [InverseProperty("CrimeType")]
    public virtual ICollection<ProcessDto> Processes { get; set; } = new List<ProcessDto>();
}