// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Processos_Juridicos.DTOs;

public partial class Harmed_or_casualtiesDTO
{
    [Key]
    public int casualties_id { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string casualties_name { get; set; }

    [InverseProperty("harmed_or_casualties")]
    public virtual ICollection<ProcessesDTO> Processes { get; set; } = new List<ProcessesDTO>();
}