// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Processos_Juridicos.DTOs;

public partial class InfringementDto
{
    [Key]
    public int InfringementId { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    [DisplayName("Acidente em Serviço")]
    public string InfringementName { get; set; }

    [InverseProperty("infringement")]
    public virtual ICollection<ProcessDto> Processes { get; set; } = new List<ProcessDto>();
}