// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Processos_Juridicos.DTOs;

public partial class Process_typesDTO
{
    [Key]
    public int process_type_id { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string process_name { get; set; }

    [InverseProperty("process_type")]
    public virtual ICollection<ProcessesDTO> Processes { get; set; } = new List<ProcessesDTO>();
}