// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Processos_Juridicos.DTOs;

public partial class Processos_DJContextDTO : DbContext
{
    public Processos_DJContextDTO(DbContextOptions<Processos_DJContextDTO> options)
        : base(options)
    {
    }

    public virtual DbSet<AccidentTypeDto> Accident_types { get; set; }

    public virtual DbSet<ProcessFileDto> Files { get; set; }

    public virtual DbSet<HarmedOrCasualtyDto> Harmed_or_casualties { get; set; }

    public virtual DbSet<InfringementDto> Infringements { get; set; }

    public virtual DbSet<ProcessTypeDto> Process_types { get; set; }

    public virtual DbSet<ProcessDto> Processes { get; set; }

    public virtual DbSet<SentenceDto> Sentences { get; set; }

    public virtual DbSet<StateDto> States { get; set; }

    public virtual DbSet<UnitDto> Units { get; set; }

    // TODO: REVIEW - REMOVE IF NECESSARY OR IF REDUNDANT
    //protected override void OnModelCreating(ModelBuilder modelBuilder)
    //{
    //    modelBuilder.Entity<ProcessTypeDto>(entity =>
    //    {
    //        entity.HasKey(e => e.ProcessTypeId).HasName("PK_Process_type");
    //    });

    //    modelBuilder.Entity<ProcessDto>(entity =>
    //    {
    //        entity.HasOne(d => d.HarmedOrCasualties).WithMany(p => p.Processes).HasConstraintName("FK_Processes_Harmed_or_casualties");

    //        entity.HasOne(d => d.Infringement).WithMany(p => p.Processes).HasConstraintName("FK_Processes_Infringements");

    //        entity.HasOne(d => d.ProcessType).WithMany(p => p.Processes).HasConstraintName("FK_Processes_Process_types");

    //        entity.HasOne(d => d.Sentence).WithMany(p => p.Processes).HasConstraintName("FK_Processes_Sentences");

    //        entity.HasOne(d => d.ServiceAccident).WithMany(p => p.Processes).HasConstraintName("FK_Processes_Accident_types");

    //        entity.HasOne(d => d.State).WithMany(p => p.Processes)
    //            .OnDelete(DeleteBehavior.ClientSetNull)
    //            .HasConstraintName("FK_Processes_States");

    //        entity.HasOne(d => d.Unit).WithMany(p => p.Processes).HasConstraintName("FK_Processes_Units");
    //    });

    //    OnModelCreatingPartial(modelBuilder);
    //}

    //partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}