// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Processos_Juridicos.DTOs;

public partial class ProcessTypeDto
{
    [Key]
    [Required]
    public int ProcessTypeId { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    [DisplayName("Nome do Tipo de Processo")]
    public string ProcessTypeName { get; set; }

    [Required]
    [DisplayName("Prazo do Processo (dias)")]
    public int Deadline { get;  set; }

    [InverseProperty("process_type")]
    public virtual ICollection<ProcessDto> Processes { get; set; } = new List<ProcessDto>();
}