// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Processos_Juridicos.DTOs;

public partial class ProcessDto
{
    [Key]
    public int ProcessId { get; set; }

    public int? Nuipm { get; set; }

    public int? ProcessTypeId { get; set; }

    public int? UnitId { get; set; }

    public int? OficialInstId { get; set; }

    public int? InvestigatedId { get; set; }

    public int? InvestigatedGenderId { get; set; }

    public DateOnly? OcurrenceDate { get; set; }

    public DateOnly? DispatchDate { get; set; }

    [Required]
    [Unicode(false)]
    public string Description { get; set; }

    public DateOnly? DeadlineDate { get; set; }

    public DateOnly? FinalDispatchDate { get; set; }

    public int? SentenceId { get; set; }

    public int StateId { get; set; }

    public DateOnly? CreatedAt { get; set; }

    public int? CreatedById { get; set; }

    public DateOnly? ModifiedAt { get; set; }

    public int? ModifiedById { get; set; }

    public int? ServiceAccidentId { get; set; }

    public int? HarmedOrCasualtiesId { get; set; }

    public double? ThirdPartyCompensation { get; set; }

    public double? Reimbursement { get; set; }

    public int? InfringementId { get; set; }

    [ForeignKey("HarmedOrCasuatiesId")]
    [InverseProperty("Processes")]
    public virtual HarmedOrCasualtyDto HarmedOrCasualties { get; set; }

    [ForeignKey("InfringementId")]
    [InverseProperty("Processes")]
    public virtual InfringementDto Infringement { get; set; }

    [ForeignKey("ProcessTypeId")]
    [InverseProperty("Processes")]
    public virtual ProcessTypeDto ProcessType { get; set; }

    [ForeignKey("SentenceId")]
    [InverseProperty("Processes")]
    public virtual SentenceDto Sentence { get; set; }

    [ForeignKey("AccidentTypeId")]
    [InverseProperty("Processes")]
    public virtual AccidentTypeDto AccidentType { get; set; }

    [ForeignKey("StateId")]
    [InverseProperty("Processes")]
    public virtual StateDto State { get; set; }

    [ForeignKey("UnitId")]
    [InverseProperty("Processes")]
    public virtual UnitDto Unit { get; set; }
}