// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Processos_Juridicos.DTOs;

public partial class ProcessesDTO
{
    [Key]
    public int process_id { get; set; }

    public int? nuipm { get; set; }

    public int? process_type_id { get; set; }

    public int? unit_id { get; set; }

    public int? oficial_inst_id { get; set; }

    public int? investigated_id { get; set; }

    public int? investigated_gender_id { get; set; }

    public DateOnly? occurrence_date { get; set; }

    public DateOnly? dispatch_date { get; set; }

    [Required]
    [Unicode(false)]
    public string description { get; set; }

    public DateOnly? deadline_date { get; set; }

    public DateOnly? final_dispatch_date { get; set; }

    public int? sentence_id { get; set; }

    public int state_id { get; set; }

    public DateOnly? created_at { get; set; }

    public int? created_by_id { get; set; }

    public DateOnly? modified_at { get; set; }

    public int? modified_by_id { get; set; }

    public int? service_accident_id { get; set; }

    public int? harmed_or_casualties_id { get; set; }

    public double? third_party_compensation { get; set; }

    public double? reimbursement { get; set; }

    public int? infringement_id { get; set; }

    [ForeignKey("harmed_or_casualties_id")]
    [InverseProperty("Processes")]
    public virtual Harmed_or_casualtiesDTO harmed_or_casualties { get; set; }

    [ForeignKey("infringement_id")]
    [InverseProperty("Processes")]
    public virtual InfringementsDTO infringement { get; set; }

    [ForeignKey("process_type_id")]
    [InverseProperty("Processes")]
    public virtual Process_typesDTO process_type { get; set; }

    [ForeignKey("sentence_id")]
    [InverseProperty("Processes")]
    public virtual SentencesDTO sentence { get; set; }

    [ForeignKey("service_accident_id")]
    [InverseProperty("Processes")]
    public virtual Accident_typesDTO service_accident { get; set; }

    [ForeignKey("state_id")]
    [InverseProperty("Processes")]
    public virtual StatesDTO state { get; set; }

    [ForeignKey("unit_id")]
    [InverseProperty("Processes")]
    public virtual Units unit { get; set; }
}