// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Processos_Juridicos.DTOs;

public partial class StateDto
{
    [Key]
    public int StateId { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string StateName { get; set; }

    [InverseProperty("state")]
    public virtual ICollection<ProcessDto> Processes { get; set; } = new List<ProcessDto>();
}