// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Processos_Juridicos.DTOs;

public partial class StatesDTO
{
    [Key]
    public int state_id { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string state_name { get; set; }

    [InverseProperty("state")]
    public virtual ICollection<ProcessesDTO> Processes { get; set; } = new List<ProcessesDTO>();
}