// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Processos_Juridicos.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Processos_Juridicos.DTOs;

public class UnitDto
{
    [Key]
    public int UnitId { get; set; }

    [DisplayName("Código da Unidade")]
    [Required(ErrorMessage = "O Código da Unidade é obrigatório")]
    public string UnitCode { get; set; }

    [Required(ErrorMessage = "O Nome da Unidade é obrigatório")]
    [StringLength(50, ErrorMessage = "O campo {0} deve ter no máximo {1} caracteres")]
    [Unicode(false)]
    [DisplayName("Nome da unidade")]
    public string UnitName { get; set; }

    [DisplayName("Abreviatura")]
    [Required(ErrorMessage = "A Sigla da Unidade é obrigatória")]
    public string UnitAcronym { get; set; }

    [Required(ErrorMessage = "É obrigatório selecionar um Setor")]
    public int SectorId { get; set; }

    public bool Enable { get; set; } = default;

    [ForeignKey("SectorId")]
    public SectorDto Sector { get; set; }

    public  ICollection<ProcessDto> Processes { get; set; } = new List<ProcessDto>();
}