// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Processos_Juridicos.DTOs;

public partial class UnitsDTO
{
    [Key]
    public string unit_code { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string unit_name { get; set; }

    [InverseProperty("unit")]
    public virtual ICollection<ProcessesDTO> Processes { get; set; } = new List<ProcessesDTO>();
}