// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Processos_Juridicos.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Processos_Juridicos.DTOs;

public  class UnitsDTO
{
    [Key]
    public string unit_code { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string unit_name { get; set; }

    public string unit_acronym { get; set; }
    public string sector_code { get; set; }


    [ForeignKey(" sector_code")]
    public SectorsDTO Sectors { get; set; }

    public  ICollection<ProcessesDTO> Processes { get; set; } = new List<ProcessesDTO>();
}